### ISSUE TITLE
npm run watch and keep compiling

### ISSUE THREAD

**Issue by durdanto-rafi** [Braunson/laravel-coreui-vue#14]
Hi,
Thanks a lot for your initiative. I cloned this repo and started working on it. After npm install, everything is working fine with npm run dev. I'm working on a mid-size application with lots of features, I often need the npm run watch. I tried but actually, can't understand the trouble. Will be very helpful if the issue is fixed.

Thanks.

**Comment by Braunson** [comment]
@durdanto-rafi What's the error you are receiving?

**Comment by durdanto-rafi** [comment]
Thanks for your quick response. Actually, there is no error! But its keep compiling and shows the toast "Build Successful" Laravel Mix.
![build successful](https://user-images.githubusercontent.com/9848528/39150765-50edba98-477e-11e8-91af-e334877209de.PNG)
![compiling](https://user-images.githubusercontent.com/9848528/39150766-511b36d0-477e-11e8-840d-0b96594d6374.PNG)

**Comment by stannyc** [comment]
I found out the problem is due to url link inside _custom-variable.scss file. I solved it by modifying the webpack.mix.js to: 
`mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .options({
      processCssUrls: false
   });`

note: if for some reason webpack won't recompile after you make changes on files, try use **npm run watch-pool** instead. This works perfectly for me

**Comment by Braunson** [comment]
@durdanto-rafi Sorry it's been a crazy few weeks, I'll look into this; this week.

@stannyc Thanks for the insight hmm

**Comment by durdanto-rafi** [comment]
@stannyc Thanks a lot! It's working fine. Though I was continuing my work by commenting out the `@import "coreui/fonts/font-awesome";
@import "coreui/fonts/simple-line-icons";`
I applied your solution and will my work according to this.

**Comment by Braunson** [comment]
@durdanto-rafi I've released an updated theme and Laravel 5.6 version that resolves these issues.
